// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { ClerkProvider } from "@clerk/nextjs";
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ClerkProvider>
//           <html lang="en">
//             <body className={inter.className}>{children}</body>
//           </html>
//         </ClerkProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

// Your default font (e.g., Inter or Geist)
// is imported here by create-next-app. Leave it as-is.
// (e.g., const inter = Inter({ subsets: ["latin"] });)

export const metadata: Metadata = {
  title: "My Canvas App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Wrap the *outside* of <html> with ClerkProvider
    <ClerkProvider>
      <html lang="en">
        {/*
          Your default className (e.g., inter.className)
          from create-next-app stays here.
        */}
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
