// import { Space } from '@/types/space';
// export const MOCK_SPACES: Space[] = [
//   {
//     id: "1",
//     name: "Product Design",
//     type: "folder",
//     items: 6,
//     updatedAt: "1d",
//     collaborators: ["user1", "user2", "user3, user4"],
//     color: "#4848ebff",
//   },
//    {
//     id: "2",
//     name: "Design Sprint",
//     type: "file",
//     items: 6,
//     updatedAt: "1d",
//     collaborators: ["user1", "user2", "user3"],
//     color: "#FF6B6B",
//   },
//     {
//     id: "3",
//     name: "Design Sprint",
//     type: "file",
//     items: 6,
//     updatedAt: "4d",
//     collaborators: ["user1", "user2", "user3"],
//     color: "#FF6B6B",
//   },
//     {
//     id: "4",
//     name: "Design Sprint",
//     type: "file",
//     items: 6,
//     updatedAt: "1d",
//     collaborators: ["user1", "user2", "user3"],
//     color: "#24da88ff",
//   },
//    {
//     id: "5",
//     name: "Product Design",
//     type: "folder",
//     items: 6,
//     updatedAt: "1d",
//     collaborators: ["user1", "user2", "user3, user4"],
//     color: "#4848ebff",
//   },
//    {
//     id: "6",
//     name: "Design Sprint",
//     type: "file",
//     items: 6,
//     updatedAt: "1d",
//     collaborators: ["user1", "user2", "user3"],
//     color: "#FF6B6B",
//   },
//     {
//     id: "7",
//     name: "Design Sprint",
//     type: "file",
//     items: 6,
//     updatedAt: "4d",
//     collaborators: ["user1", "user2", "user3"],
//     color: "#FF6B6B",
//   },
//     {
//     id: "8",
//     name: "Design Sprint",
//     type: "file",
//     items: 6,
//     updatedAt: "1d",
//     collaborators: ["user1", "user2", "user3"],
//     color: "#24da88ff",
//   },
//   // ... rest of your spaces data
// ];
