-- AlterTable
ALTER TABLE "files" ADD COLUMN     "positionX" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "positionY" DOUBLE PRECISION DEFAULT 0;

-- AlterTable
ALTER TABLE "folders" ADD COLUMN     "positionX" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "positionY" DOUBLE PRECISION DEFAULT 0;
